[build]
  command = "npm install --legacy-peer-deps && npm run build"
  functions = "netlify/functions"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"
  CI = "false"

[dev]
  framework  = "#custom"
  command    = "npm start"
  targetPort = 3000
  port       = 8888

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
